sonar.projectKey=cashin-express-authz

sonar.sources=src
sonar.tests=test

sonar.exclusions=node_modules/**,build/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
